# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kernel < Formula
  desc "Kernel CLI"
  homepage "https://github.com/kernel/cli"
  version "0.47.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kernel/cli/releases/download/v0.47.0/kernel_0.47.0_darwin_amd64.tar.gz"
      sha256 "6f081d5089b8a631cdaaea24fd8af98017b40be121f542c54f0a5f08e6c30294"

      define_method(:install) do
        bin.install "kernel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kernel/cli/releases/download/v0.47.0/kernel_0.47.0_darwin_arm64.tar.gz"
      sha256 "5103cb9abf80bc6dfe8d58913338e7e0af8862c032c9a901f7252d4124910d9c"

      define_method(:install) do
        bin.install "kernel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/cli/releases/download/v0.47.0/kernel_0.47.0_linux_amd64.tar.gz"
      sha256 "36a1bfbc4a47ca5991b6a5b77ae549fa11cb0034809c1d6159c72697d67bf5c6"
      define_method(:install) do
        bin.install "kernel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/cli/releases/download/v0.47.0/kernel_0.47.0_linux_arm64.tar.gz"
      sha256 "2956f57c232ddb7868be28fdc94cb8b3c00c124ff977309c37a40bcca8f16c42"
      define_method(:install) do
        bin.install "kernel"
      end
    end
  end

  test do
    system "#{bin}/kernel", "--version"
  end
end
