# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kernel < Formula
  desc "Kernel CLI"
  homepage "https://github.com/kernel/cli"
  version "0.46.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kernel/cli/releases/download/v0.46.0/kernel_0.46.0_darwin_amd64.tar.gz"
      sha256 "614aef98437327413af6adfa70a429920c097b59171b2d53bdeceefc8b079c29"

      define_method(:install) do
        bin.install "kernel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kernel/cli/releases/download/v0.46.0/kernel_0.46.0_darwin_arm64.tar.gz"
      sha256 "9479c7ef70b6618b48875f857ee8707be9520c78821b4906b81cb124219efd95"

      define_method(:install) do
        bin.install "kernel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/cli/releases/download/v0.46.0/kernel_0.46.0_linux_amd64.tar.gz"
      sha256 "9fb8cdef1f1a91cc499c13af13d7a122de932525418992452cacb08d81ee9de6"
      define_method(:install) do
        bin.install "kernel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/cli/releases/download/v0.46.0/kernel_0.46.0_linux_arm64.tar.gz"
      sha256 "546d70a3a2eee2641371c9d6251d81e6d2ca5bc4eb2297828567a528d680a5a1"
      define_method(:install) do
        bin.install "kernel"
      end
    end
  end

  test do
    system "#{bin}/kernel", "--version"
  end
end
