# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kernel < Formula
  desc "Kernel CLI"
  homepage "https://github.com/kernel/cli"
  version "0.45.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kernel/cli/releases/download/v0.45.0/kernel_0.45.0_darwin_amd64.tar.gz"
      sha256 "5a29b78def715ef2a35770d6e362e0ff7f1776e270e32090f8c393fd8d85272b"

      define_method(:install) do
        bin.install "kernel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kernel/cli/releases/download/v0.45.0/kernel_0.45.0_darwin_arm64.tar.gz"
      sha256 "ec11cca74a6094212cd8fec2cf7336caa86cd4d15e2f3453a65e34184027f133"

      define_method(:install) do
        bin.install "kernel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/cli/releases/download/v0.45.0/kernel_0.45.0_linux_amd64.tar.gz"
      sha256 "957b940967f518caf005901c013eb07d8d579c497daab9a3e5017774d48325c6"
      define_method(:install) do
        bin.install "kernel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/cli/releases/download/v0.45.0/kernel_0.45.0_linux_arm64.tar.gz"
      sha256 "03623ba1d22a9c472b3fe6d2cdc2fd73a729f413191000f18440970396e8f433"
      define_method(:install) do
        bin.install "kernel"
      end
    end
  end

  test do
    system "#{bin}/kernel", "--version"
  end
end
